create database QUEUE
use QUEUE
CREATE TABLE PROJECT
(
PID INT PRIMARY KEY,
PNAME VARCHAR(100),
CID INT REFERENCES CLIE(CID) ,
PSD DATE,
PED DATE,
STATP VARCHAR(100)
);

CREATE TABLE CLIE
(
CID INT PRIMARY KEY,
CNAME VARCHAR(100),
STATC VARCHAR(100)
);

CREATE TABLE RESOURCES
(
EID INT PRIMARY KEY,
ENAME VARCHAR(100),
DOB DATE,
DOJ DATE,
DESIGNATION VARCHAR(100),
DEPARTMENT VARCHAR(100),
COUNTRY VARCHAR(100),
EMAIL VARCHAR(100),
CONTACT VARCHAR(100),
Skillset VARCHAR(100),
STATR VARCHAR(100)
);

Create Table Allocation
(
AID INT PRIMARY KEY,
PID INT REFERENCES PROJECT(PID),
EID INT REFERENCES RESOURCES(EID),
FROM_DATE DATE,
TO_DATE DATE,
HOURS INT,
Skillset varchar(100)
);
Create Table Login
(
Username VARCHAR(100),
Password VARCHAR(100)
);
